In [11]:
import numpy as np

In [12]:
def sig(z):
    return 1/(1 + np.exp(-z))


In [13]:
def derivativeSig(sig_out):
    return sig_out*(1 - sig_out)

In [14]:
x = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y = np.array([[0,0,1,1]]).T

In [15]:
weights = 2 * np.random.random((3,1)) - 1
weights

array([[-0.26790984],
       [ 0.1563845 ],
       [ 0.5247328 ]])

In [16]:
output0 = x
output1 = sig(np.dot(output0 , weights))
output1

array([[ 0.62825379],
       [ 0.66398802],
       [ 0.56385515],
       [ 0.60185672]])

In [17]:
output0 = x
output1 = sig(np.dot(output0 , weights))
output1
first_term = output1 - y

In [18]:
output0 = x
output1 = sig(np.dot(output0 , weights))
output1
first_term = output1 - y
second_term = derivativeSig(output1)
learning_rate = 0.1

In [22]:
for iter in range(1000):    
    output0 = x
    output1 = sig(np.dot(output0 , weights))
    output1
    first_term = output1 - y
    second_term = derivativeSig(output1)
    learning_rate = 0.1
    third_term = output0
    first_two = first_term * second_term
    changes = np.array([[0,0,0.0]])
    for i in range(2):
        for j in range(4):
            changes[0][i] = changes[0][i] + first_two[j][0]*third_term[j][i]
    # np.dot(output0.T,first_two)
    weights = weights - learning_rate*changes.T
weights,output1

(array([[ 4.58842   ],
        [-2.69877675],
        [ 0.5247328 ]]), array([[ 0.62825379],
        [ 0.10213483],
        [ 0.99401521],
        [ 0.91789405]]))

In [25]:
weights0 = 2*np.random.random((3,4)) - 1
weights1 = 2* np.random.random((4,1)) - 1

In [ ]:
for iter in range(100000000000000):       
    layer0 = x
    layer1 = sig(np.dot(layer0,weights0))
    layer2 = sig(np.dot(layer1,weights1))
    l2_error = layer2 - y
    l2_delta = l2_error * derivativeSig(layer2)
    net_change2 = np.dot(layer1.T,l2_delta)
    l1_error = l2_delta.dot(weights1.T)
    l1_delta = l1_error * derivativeSig(layer1)
    net_change1 = np.dot(layer0.T,l1_delta)
    net_change2.shape
    weights0 = weights0 - learning_rate*net_change1
    weights1 = weights1 - learning_rate*net_change2

layer0 = x
layer1 = sig(np.dot(layer0,weights0))
layer2 = sig(np.dot(layer1,weights1))
layer2